spring.datasource.url: jdbc:mysql://localhost:3306/forrum?useUnicode=true&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: 2002
spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.initialization-mode: always
spring.jpa.show-sql: false

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005

blog.default.page.limit: 10
blog.announce.length: 150
blog.captcha.lifetime.minutes: 5
blog.captcha.width: 100
blog.captcha.height: 35

blog.restore.password.link.lifetime.minutes: 3

blog.multiuser.mode: true
blog.post.premoderation: true
blog.statistic.is.public: false

blog.email.sender: forrumdevpub@gmail.com
blog.email.sender.password: burduninkonstantin
blog.email.sender.host: smtp.gmail.com
blog.email.sender.port: 587
blog.email.sender.protocol: smtp
blog.email.sender.smtp.auth: true
blog.email.sender.smtp.starttls.enable: true
blog.email.sender.debug: true
blog.email.sender.email.text.filename: restoreEmailText.txt
blog.email.sender.email.text.nameoffset: 9

upload.path: upload
avatars.path: upload_avatars






